# SPDX-License-Identifier: GPL-2.0-or-later
# Use case configuration for Xiaomi Mi Max 2
# Earpiece, headphones and microphones are on the internal PM8953 codec.
# The loudspeakers are two TI TAS2560 amplifiers on Quinary MI2S
# (MultiMedia3, hw:${CardId},2). Their Speaker device is added once the
# TAS2560 driver exists.

SectionVerb {
	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer TERT_MI2S_TX' 1"
		cset "name='PRI_MI2S_RX Voice Mixer VoiceMMode1' 1"
		cset "name='VoiceMMode1 Capture Mixer TERT_MI2S_TX' 1"
	]
	DisableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer TERT_MI2S_TX' 0"
		cset "name='PRI_MI2S_RX Voice Mixer VoiceMMode1' 0"
		cset "name='VoiceMMode1 Capture Mixer TERT_MI2S_TX' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece playback"

	ConflictingDevice [
		"Headphones"
	]

	Include.ees.File "/codecs/msm8953-wcd/EarpieceEnableSeq.conf"
	Include.eds.File "/codecs/msm8953-wcd/EarpieceDisableSeq.conf"

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 100
		PlaybackChannels 1
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"

	ConflictingDevice [
		"Earpiece"
	]

	Include.hpes.File "/codecs/msm8953-wcd/HeadphonesEnableSeq.conf"
	Include.hpds.File "/codecs/msm8953-wcd/HeadphonesDisableSeq.conf"

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 300
		PlaybackChannels 2
		JackControl "Headphone Jack"
	}
}

SectionDevice."Mic1" {
	Comment "Primary Microphone"

	ConflictingDevice [
		"Headset"
		"Mic2"
	]

	Include.pmes.File "/codecs/msm8953-wcd/PrimaryMicEnableSeq.conf"
	Include.pmds.File "/codecs/msm8953-wcd/PrimaryMicDisableSeq.conf"

	Value {
		CapturePCM "hw:${CardId},1"
		CaptureChannels 1
		CapturePriority 300
	}
}

SectionDevice."Mic2" {
	Comment "Secondary Microphone"

	ConflictingDevice [
		"Headset"
		"Mic1"
	]

	Include.smes.File "/codecs/msm8953-wcd/SecondaryMicEnableSeq.conf"
	Include.smds.File "/codecs/msm8953-wcd/SecondaryMicDisableSeq.conf"

	Value {
		CapturePCM "hw:${CardId},1"
		CaptureChannels 1
		CapturePriority 200
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	ConflictingDevice [
		"Mic1"
		"Mic2"
	]

	Include.hmes.File "/codecs/msm8953-wcd/HeadsetMicEnableSeq.conf"
	Include.hmds.File "/codecs/msm8953-wcd/HeadsetMicDisableSeq.conf"

	Value {
		CapturePCM "hw:${CardId},1"
		CaptureChannels 1
		CapturePriority 400
		JackControl "Mic Jack"
	}
}
